export const planetsSearch = [ { id: 'cGxhbmV0czox',
name: 'Tatooine',
diameter: 10465,
rotationPeriod: 23,
orbitalPeriod: 304,
gravity: '1 standard',
population: 200000,
climates: [ 'arid' ],
terrains: [ 'desert' ],
surfaceWater: 1 },
{ id: 'cGxhbmV0czoy',
name: 'Alderaan',
diameter: 12500,
rotationPeriod: 24,
orbitalPeriod: 364,
gravity: '1 standard',
population: 2000000000,
climates: [ 'temperate' ],
terrains: [ 'grasslands', 'mountains' ],
surfaceWater: 40 },
{ id: 'cGxhbmV0czoz',
name: 'Yavin IV',
diameter: 10200,
rotationPeriod: 24,
orbitalPeriod: 4818,
gravity: '1 standard',
population: 1000,
climates: [ 'temperate', 'tropical' ],
terrains: [ 'jungle', 'rainforests' ],
surfaceWater: 8 },
{ id: 'cGxhbmV0czo0',
name: 'Hoth',
diameter: 7200,
rotationPeriod: 23,
orbitalPeriod: 549,
gravity: '1.1 standard',
population: null,
climates: [ 'frozen' ],
terrains: [ 'tundra', 'ice caves', 'mountain ranges' ],
surfaceWater: 100 },
{ id: 'cGxhbmV0czo1',
name: 'Dagobah',
diameter: 8900,
rotationPeriod: 23,
orbitalPeriod: 341,
gravity: 'N/A',
population: null,
climates: [ 'murky' ],
terrains: [ 'swamp', 'jungles' ],
surfaceWater: 8 },
{ id: 'cGxhbmV0czo2',
name: 'Bespin',
diameter: 118000,
rotationPeriod: 12,
orbitalPeriod: 5110,
gravity: '1.5 (surface), 1 standard (Cloud City)',
population: 6000000,
climates: [ 'temperate' ],
terrains: [ 'gas giant' ],
surfaceWater: 0 },
{ id: 'cGxhbmV0czo3',
name: 'Endor',
diameter: 4900,
rotationPeriod: 18,
orbitalPeriod: 402,
gravity: '0.85 standard',
population: 30000000,
climates: [ 'temperate' ],
terrains: [ 'forests', 'mountains', 'lakes' ],
surfaceWater: 8 },
{ id: 'cGxhbmV0czo4',
name: 'Naboo',
diameter: 12120,
rotationPeriod: 26,
orbitalPeriod: 312,
gravity: '1 standard',
population: 4500000000,
climates: [ 'temperate' ],
terrains: [ 'grassy hills', 'swamps', 'forests', 'mountains' ],
surfaceWater: 12 },
{ id: 'cGxhbmV0czo5',
name: 'Coruscant',
diameter: 12240,
rotationPeriod: 24,
orbitalPeriod: 368,
gravity: '1 standard',
population: 1000000000000,
climates: [ 'temperate' ],
terrains: [ 'cityscape', 'mountains' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoxMA==',
name: 'Kamino',
diameter: 19720,
rotationPeriod: 27,
orbitalPeriod: 463,
gravity: '1 standard',
population: 1000000000,
climates: [ 'temperate' ],
terrains: [ 'ocean' ],
surfaceWater: 100 },
{ id: 'cGxhbmV0czoxMQ==',
name: 'Geonosis',
diameter: 11370,
rotationPeriod: 30,
orbitalPeriod: 256,
gravity: '0.9 standard',
population: 100000000000,
climates: [ 'temperate', 'arid' ],
terrains: [ 'rock', 'desert', 'mountain', 'barren' ],
surfaceWater: 5 },
{ id: 'cGxhbmV0czoxMg==',
name: 'Utapau',
diameter: 12900,
rotationPeriod: 27,
orbitalPeriod: 351,
gravity: '1 standard',
population: 95000000,
climates: [ 'temperate', 'arid', 'windy' ],
terrains: [ 'scrublands', 'savanna', 'canyons', 'sinkholes' ],
surfaceWater: 0.9 },
{ id: 'cGxhbmV0czoxMw==',
name: 'Mustafar',
diameter: 4200,
rotationPeriod: 36,
orbitalPeriod: 412,
gravity: '1 standard',
population: 20000,
climates: [ 'hot' ],
terrains: [ 'volcanoes', 'lava rivers', 'mountains', 'caves' ],
surfaceWater: 0 },
{ id: 'cGxhbmV0czoxNA==',
name: 'Kashyyyk',
diameter: 12765,
rotationPeriod: 26,
orbitalPeriod: 381,
gravity: '1 standard',
population: 45000000,
climates: [ 'tropical' ],
terrains: [ 'jungle', 'forests', 'lakes', 'rivers' ],
surfaceWater: 60 },
{ id: 'cGxhbmV0czoxNQ==',
name: 'Polis Massa',
diameter: 0,
rotationPeriod: 24,
orbitalPeriod: 590,
gravity: '0.56 standard',
population: 1000000,
climates: [ 'artificial temperate' ],
terrains: [ 'airless asteroid' ],
surfaceWater: 0 },
{ id: 'cGxhbmV0czoxNg==',
name: 'Mygeeto',
diameter: 10088,
rotationPeriod: 12,
orbitalPeriod: 167,
gravity: '1 standard',
population: 19000000,
climates: [ 'frigid' ],
terrains: [ 'glaciers', 'mountains', 'ice canyons' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoxNw==',
name: 'Felucia',
diameter: 9100,
rotationPeriod: 34,
orbitalPeriod: 231,
gravity: '0.75 standard',
population: 8500000,
climates: [ 'hot', 'humid' ],
terrains: [ 'fungus forests' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoxOA==',
name: 'Cato Neimoidia',
diameter: 0,
rotationPeriod: 25,
orbitalPeriod: 278,
gravity: '1 standard',
population: 10000000,
climates: [ 'temperate', 'moist' ],
terrains: [ 'mountains', 'fields', 'forests', 'rock arches' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoxOQ==',
name: 'Saleucami',
diameter: 14920,
rotationPeriod: 26,
orbitalPeriod: 392,
gravity: 'unknown',
population: 1400000000,
climates: [ 'hot' ],
terrains: [ 'caves', 'desert', 'mountains', 'volcanoes' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoyMA==',
name: 'Stewjon',
diameter: 0,
rotationPeriod: null,
orbitalPeriod: null,
gravity: '1 standard',
population: null,
climates: [ 'temperate' ],
terrains: [ 'grass' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoyMQ==',
name: 'Eriadu',
diameter: 13490,
rotationPeriod: 24,
orbitalPeriod: 360,
gravity: '1 standard',
population: 22000000000,
climates: [ 'polluted' ],
terrains: [ 'cityscape' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoyMg==',
name: 'Corellia',
diameter: 11000,
rotationPeriod: 25,
orbitalPeriod: 329,
gravity: '1 standard',
population: 3000000000,
climates: [ 'temperate' ],
terrains: [ 'plains', 'urban', 'hills', 'forests' ],
surfaceWater: 70 },
{ id: 'cGxhbmV0czoyMw==',
name: 'Rodia',
diameter: 7549,
rotationPeriod: 29,
orbitalPeriod: 305,
gravity: '1 standard',
population: 1300000000,
climates: [ 'hot' ],
terrains: [ 'jungles', 'oceans', 'urban', 'swamps' ],
surfaceWater: 60 },
{ id: 'cGxhbmV0czoyNA==',
name: 'Nal Hutta',
diameter: 12150,
rotationPeriod: 87,
orbitalPeriod: 413,
gravity: '1 standard',
population: 7000000000,
climates: [ 'temperate' ],
terrains: [ 'urban', 'oceans', 'swamps', 'bogs' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoyNQ==',
name: 'Dantooine',
diameter: 9830,
rotationPeriod: 25,
orbitalPeriod: 378,
gravity: '1 standard',
population: 1000,
climates: [ 'temperate' ],
terrains: [ 'oceans', 'savannas', 'mountains', 'grasslands' ],
surfaceWater: null },
{ id: 'cGxhbmV0czoyNg==',
name: 'Bestine IV',
diameter: 6400,
rotationPeriod: 26,
orbitalPeriod: 680,
gravity: 'unknown',
population: 62000000,
climates: [ 'temperate' ],
terrains: [ 'rocky islands', 'oceans' ],
surfaceWater: 98 }
]