export const speciesSearch = [ { id: 'c3BlY2llczox',
name: 'Human',
classification: 'mammal',
designation: 'sentient',
averageHeight: 180,
averageLifespan: 120,
eyeColors: [ 'brown', 'blue', 'green', 'hazel', 'grey', 'amber' ],
hairColors: [ 'blonde', 'brown', 'black', 'red' ],
skinColors: [ 'caucasian', 'black', 'asian', 'hispanic' ],
language: 'Galactic Basic' },
{ id: 'c3BlY2llczoy',
name: 'Droid',
classification: 'artificial',
designation: 'sentient',
averageHeight: null,
averageLifespan: null,
eyeColors: [ 'n/a' ],
hairColors: [ 'n/a' ],
skinColors: [ 'n/a' ],
language: 'n/a' },
{ id: 'c3BlY2llczoz',
name: 'Wookiee',
classification: 'mammal',
designation: 'sentient',
averageHeight: 210,
averageLifespan: 400,
eyeColors: [ 'blue', 'green', 'yellow', 'brown', 'golden', 'red' ],
hairColors: [ 'black', 'brown' ],
skinColors: [ 'gray' ],
language: 'Shyriiwook' },
{ id: 'c3BlY2llczo0',
name: 'Rodian',
classification: 'sentient',
designation: 'reptilian',
averageHeight: 170,
averageLifespan: null,
eyeColors: [ 'black' ],
hairColors: [ 'n/a' ],
skinColors: [ 'green', 'blue' ],
language: 'Galactic Basic' },
{ id: 'c3BlY2llczo1',
name: 'Hutt',
classification: 'gastropod',
designation: 'sentient',
averageHeight: 300,
averageLifespan: 1000,
eyeColors: [ 'yellow', 'red' ],
hairColors: [ 'n/a' ],
skinColors: [ 'green', 'brown', 'tan' ],
language: 'Huttese' },
{ id: 'c3BlY2llczo2',
name: 'Yoda\'s species',
classification: 'mammal',
designation: 'sentient',
averageHeight: 66,
averageLifespan: 900,
eyeColors: [ 'brown', 'green', 'yellow' ],
hairColors: [ 'brown', 'white' ],
skinColors: [ 'green', 'yellow' ],
language: 'Galactic basic' },
{ id: 'c3BlY2llczo3',
name: 'Trandoshan',
classification: 'reptile',
designation: 'sentient',
averageHeight: 200,
averageLifespan: null,
eyeColors: [ 'yellow', 'orange' ],
hairColors: [],
skinColors: [ 'brown', 'green' ],
language: 'Dosh' },
{ id: 'c3BlY2llczo4',
name: 'Mon Calamari',
classification: 'amphibian',
designation: 'sentient',
averageHeight: 160,
averageLifespan: null,
eyeColors: [ 'yellow' ],
hairColors: [],
skinColors: [ 'red', 'blue', 'brown', 'magenta' ],
language: 'Mon Calamarian' },
{ id: 'c3BlY2llczo5',
name: 'Ewok',
classification: 'mammal',
designation: 'sentient',
averageHeight: 100,
averageLifespan: null,
eyeColors: [ 'orange', 'brown' ],
hairColors: [ 'white', 'brown', 'black' ],
skinColors: [ 'brown' ],
language: 'Ewokese' },
{ id: 'c3BlY2llczoxMA==',
name: 'Sullustan',
classification: 'mammal',
designation: 'sentient',
averageHeight: 180,
averageLifespan: null,
eyeColors: [ 'black' ],
hairColors: [],
skinColors: [ 'pale' ],
language: 'Sullutese' },
{ id: 'c3BlY2llczoxMQ==',
name: 'Neimodian',
classification: 'unknown',
designation: 'sentient',
averageHeight: 180,
averageLifespan: null,
eyeColors: [ 'red', 'pink' ],
hairColors: [],
skinColors: [ 'grey', 'green' ],
language: 'Neimoidia' },
{ id: 'c3BlY2llczoxMg==',
name: 'Gungan',
classification: 'amphibian',
designation: 'sentient',
averageHeight: 190,
averageLifespan: null,
eyeColors: [ 'orange' ],
hairColors: [],
skinColors: [ 'brown', 'green' ],
language: 'Gungan basic' },
{ id: 'c3BlY2llczoxMw==',
name: 'Toydarian',
classification: 'mammal',
designation: 'sentient',
averageHeight: 120,
averageLifespan: 91,
eyeColors: [ 'yellow' ],
hairColors: [],
skinColors: [ 'blue', 'green', 'grey' ],
language: 'Toydarian' },
{ id: 'c3BlY2llczoxNA==',
name: 'Dug',
classification: 'mammal',
designation: 'sentient',
averageHeight: 100,
averageLifespan: null,
eyeColors: [ 'yellow', 'blue' ],
hairColors: [],
skinColors: [ 'brown', 'purple', 'grey', 'red' ],
language: 'Dugese' },
{ id: 'c3BlY2llczoxNQ==',
name: 'Twi\'lek',
classification: 'mammals',
designation: 'sentient',
averageHeight: 200,
averageLifespan: null,
eyeColors: [ 'blue', 'brown', 'orange', 'pink' ],
hairColors: [],
skinColors: [ 'orange', 'yellow', 'blue', 'green', 'pink', 'purple', 'tan' ],
language: 'Twi\'leki' },
{ id: 'c3BlY2llczoxNg==',
name: 'Aleena',
classification: 'reptile',
designation: 'sentient',
averageHeight: 80,
averageLifespan: 79,
eyeColors: [ 'unknown' ],
hairColors: [],
skinColors: [ 'blue', 'gray' ],
language: 'Aleena' },
{ id: 'c3BlY2llczoxNw==',
name: 'Vulptereen',
classification: 'unknown',
designation: 'sentient',
averageHeight: 100,
averageLifespan: null,
eyeColors: [ 'yellow' ],
hairColors: [],
skinColors: [ 'grey' ],
language: 'vulpterish' },
{ id: 'c3BlY2llczoxOA==',
name: 'Xexto',
classification: 'unknown',
designation: 'sentient',
averageHeight: 125,
averageLifespan: null,
eyeColors: [ 'black' ],
hairColors: [],
skinColors: [ 'grey', 'yellow', 'purple' ],
language: 'Xextese' },
{ id: 'c3BlY2llczoxOQ==',
name: 'Toong',
classification: 'unknown',
designation: 'sentient',
averageHeight: 200,
averageLifespan: null,
eyeColors: [ 'orange' ],
hairColors: [],
skinColors: [ 'grey', 'green', 'yellow' ],
language: 'Tundan' },
{ id: 'c3BlY2llczoyMA==',
name: 'Cerean',
classification: 'mammal',
designation: 'sentient',
averageHeight: 200,
averageLifespan: null,
eyeColors: [ 'hazel' ],
hairColors: [ 'red', 'blond', 'black', 'white' ],
skinColors: [ 'pale pink' ],
language: 'Cerean' },
{ id: 'c3BlY2llczoyMQ==',
name: 'Nautolan',
classification: 'amphibian',
designation: 'sentient',
averageHeight: 180,
averageLifespan: 70,
eyeColors: [ 'black' ],
hairColors: [],
skinColors: [ 'green', 'blue', 'brown', 'red' ],
language: 'Nautila' },
{ id: 'c3BlY2llczoyMg==',
name: 'Zabrak',
classification: 'mammal',
designation: 'sentient',
averageHeight: 180,
averageLifespan: null,
eyeColors: [ 'brown', 'orange' ],
hairColors: [ 'black' ],
skinColors: [ 'pale', 'brown', 'red', 'orange', 'yellow' ],
language: 'Zabraki' },
{ id: 'c3BlY2llczoyMw==',
name: 'Tholothian',
classification: 'mammal',
designation: 'sentient',
averageHeight: null,
averageLifespan: null,
eyeColors: [ 'blue', 'indigo' ],
hairColors: [ 'unknown' ],
skinColors: [ 'dark' ],
language: 'unknown' },
{ id: 'c3BlY2llczoyNA==',
name: 'Iktotchi',
classification: 'unknown',
designation: 'sentient',
averageHeight: 180,
averageLifespan: null,
eyeColors: [ 'orange' ],
hairColors: [],
skinColors: [ 'pink' ],
language: 'Iktotchese' },
{ id: 'c3BlY2llczoyNQ==',
name: 'Quermian',
classification: 'mammal',
designation: 'sentient',
averageHeight: 240,
averageLifespan: 86,
eyeColors: [ 'yellow' ],
hairColors: [],
skinColors: [ 'white' ],
language: 'Quermian' },
{ id: 'c3BlY2llczoyNg==',
name: 'Kel Dor',
classification: 'unknown',
designation: 'sentient',
averageHeight: 180,
averageLifespan: 70,
eyeColors: [ 'black', 'silver' ],
hairColors: [],
skinColors: [ 'peach', 'orange', 'red' ],
language: 'Kel Dor' },
{ id: 'c3BlY2llczoyNw==',
name: 'Chagrian',
classification: 'amphibian',
designation: 'sentient',
averageHeight: 190,
averageLifespan: null,
eyeColors: [ 'blue' ],
hairColors: [],
skinColors: [ 'blue' ],
language: 'Chagria' },
{ id: 'c3BlY2llczoyOA==',
name: 'Geonosian',
classification: 'insectoid',
designation: 'sentient',
averageHeight: 178,
averageLifespan: null,
eyeColors: [ 'green', 'hazel' ],
hairColors: [],
skinColors: [ 'green', 'brown' ],
language: 'Geonosian' },
{ id: 'c3BlY2llczoyOQ==',
name: 'Mirialan',
classification: 'mammal',
designation: 'sentient',
averageHeight: 180,
averageLifespan: null,
eyeColors: [ 'blue', 'green', 'red', 'yellow', 'brown', 'orange' ],
hairColors: [ 'black', 'brown' ],
skinColors: [ 'yellow', 'green' ],
language: 'Mirialan' }]