export const vehiclesSearch = [ { id: 'dmVoaWNsZXM6NA==',
name: 'Sand Crawler',
model: 'Digger Crawler',
vehicleClass: 'wheeled',
manufacturers: [ 'Corellia Mining Corporation' ],
costInCredits: 150000,
length: 36.8,
crew: '46',
passengers: '30',
maxAtmospheringSpeed: 30,
cargoCapacity: 50000,
consumables: '2 months' },
{ id: 'dmVoaWNsZXM6Ng==',
name: 'T-16 skyhopper',
model: 'T-16 skyhopper',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'Incom Corporation' ],
costInCredits: 14500,
length: 10.4,
crew: '1',
passengers: '1',
maxAtmospheringSpeed: 1200,
cargoCapacity: 50,
consumables: '0' },
{ id: 'dmVoaWNsZXM6Nw==',
name: 'X-34 landspeeder',
model: 'X-34 landspeeder',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'SoroSuub Corporation' ],
costInCredits: 10550,
length: 3.4,
crew: '1',
passengers: '1',
maxAtmospheringSpeed: 250,
cargoCapacity: 5,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6OA==',
name: 'TIE/LN starfighter',
model: 'Twin Ion Engine/Ln Starfighter',
vehicleClass: 'starfighter',
manufacturers: [ 'Sienar Fleet Systems' ],
costInCredits: null,
length: 6.4,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 1200,
cargoCapacity: 65,
consumables: '2 days' },
{ id: 'dmVoaWNsZXM6MTQ=',
name: 'Snowspeeder',
model: 't-47 airspeeder',
vehicleClass: 'airspeeder',
manufacturers: [ 'Incom corporation' ],
costInCredits: null,
length: 4.5,
crew: '2',
passengers: '0',
maxAtmospheringSpeed: 650,
cargoCapacity: 10,
consumables: 'none' },
{ id: 'dmVoaWNsZXM6MTY=',
name: 'TIE bomber',
model: 'TIE/sa bomber',
vehicleClass: 'space/planetary bomber',
manufacturers: [ 'Sienar Fleet Systems' ],
costInCredits: null,
length: 7.8,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 850,
cargoCapacity: null,
consumables: '2 days' },
{ id: 'dmVoaWNsZXM6MTg=',
name: 'AT-AT',
model: 'All Terrain Armored Transport',
vehicleClass: 'assault walker',
manufacturers:
 [ 'Kuat Drive Yards',
   'Imperial Department of Military Research' ],
costInCredits: null,
length: 20,
crew: '5',
passengers: '40',
maxAtmospheringSpeed: 60,
cargoCapacity: 1000,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6MTk=',
name: 'AT-ST',
model: 'All Terrain Scout Transport',
vehicleClass: 'walker',
manufacturers:
 [ 'Kuat Drive Yards',
   'Imperial Department of Military Research' ],
costInCredits: null,
length: 2,
crew: '2',
passengers: '0',
maxAtmospheringSpeed: 90,
cargoCapacity: 200,
consumables: 'none' },
{ id: 'dmVoaWNsZXM6MjA=',
name: 'Storm IV Twin-Pod cloud car',
model: 'Storm IV Twin-Pod',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'Bespin Motors' ],
costInCredits: 75000,
length: 7,
crew: '2',
passengers: '0',
maxAtmospheringSpeed: 1500,
cargoCapacity: 10,
consumables: '1 day' },
{ id: 'dmVoaWNsZXM6MjQ=',
name: 'Sail barge',
model: 'Modified Luxury Sail Barge',
vehicleClass: 'sail barge',
manufacturers: [ 'Ubrikkian Industries Custom Vehicle Division' ],
costInCredits: 285000,
length: 30,
crew: '26',
passengers: '500',
maxAtmospheringSpeed: 100,
cargoCapacity: 2000000,
consumables: 'Live food tanks' },
{ id: 'dmVoaWNsZXM6MjU=',
name: 'Bantha-II cargo skiff',
model: 'Bantha-II',
vehicleClass: 'repulsorcraft cargo skiff',
manufacturers: [ 'Ubrikkian Industries' ],
costInCredits: 8000,
length: 9.5,
crew: '5',
passengers: '16',
maxAtmospheringSpeed: 250,
cargoCapacity: 135000,
consumables: '1 day' },
{ id: 'dmVoaWNsZXM6MjY=',
name: 'TIE/IN interceptor',
model: 'Twin Ion Engine Interceptor',
vehicleClass: 'starfighter',
manufacturers: [ 'Sienar Fleet Systems' ],
costInCredits: null,
length: 9.6,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 1250,
cargoCapacity: 75,
consumables: '2 days' },
{ id: 'dmVoaWNsZXM6MzA=',
name: 'Imperial Speeder Bike',
model: '74-Z speeder bike',
vehicleClass: 'speeder',
manufacturers: [ 'Aratech Repulsor Company' ],
costInCredits: 8000,
length: 3,
crew: '1',
passengers: '1',
maxAtmospheringSpeed: 360,
cargoCapacity: 4,
consumables: '1 day' },
{ id: 'dmVoaWNsZXM6MzM=',
name: 'Vulture Droid',
model: 'Vulture-class droid starfighter',
vehicleClass: 'starfighter',
manufacturers: [ 'Haor Chall Engineering', 'Baktoid Armor Workshop' ],
costInCredits: null,
length: 3.5,
crew: '0',
passengers: '0',
maxAtmospheringSpeed: 1200,
cargoCapacity: 0,
consumables: 'none' },
{ id: 'dmVoaWNsZXM6MzQ=',
name: 'Multi-Troop Transport',
model: 'Multi-Troop Transport',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'Baktoid Armor Workshop' ],
costInCredits: 138000,
length: 31,
crew: '4',
passengers: '112',
maxAtmospheringSpeed: 35,
cargoCapacity: 12000,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6MzU=',
name: 'Armored Assault Tank',
model: 'Armoured Assault Tank',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'Baktoid Armor Workshop' ],
costInCredits: null,
length: 9.75,
crew: '4',
passengers: '6',
maxAtmospheringSpeed: 55,
cargoCapacity: null,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6MzY=',
name: 'Single Trooper Aerial Platform',
model: 'Single Trooper Aerial Platform',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'Baktoid Armor Workshop' ],
costInCredits: 2500,
length: 2,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 400,
cargoCapacity: null,
consumables: 'none' },
{ id: 'dmVoaWNsZXM6Mzc=',
name: 'C-9979 landing craft',
model: 'C-9979 landing craft',
vehicleClass: 'landing craft',
manufacturers: [ 'Haor Chall Engineering' ],
costInCredits: 200000,
length: 210,
crew: '140',
passengers: '284',
maxAtmospheringSpeed: 587,
cargoCapacity: 1800000,
consumables: '1 day' },
{ id: 'dmVoaWNsZXM6Mzg=',
name: 'Tribubble bongo',
model: 'Tribubble bongo',
vehicleClass: 'submarine',
manufacturers: [ 'Otoh Gunga Bongameken Cooperative' ],
costInCredits: null,
length: 15,
crew: '1',
passengers: '2',
maxAtmospheringSpeed: 85,
cargoCapacity: 1600,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NDI=',
name: 'Sith speeder',
model: 'FC-20 speeder bike',
vehicleClass: 'speeder',
manufacturers: [ 'Razalon' ],
costInCredits: 4000,
length: 1.5,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 180,
cargoCapacity: 2,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NDQ=',
name: 'Zephyr-G swoop bike',
model: 'Zephyr-G swoop bike',
vehicleClass: 'repulsorcraft',
manufacturers: [ 'Mobquet Swoops and Speeders' ],
costInCredits: 5750,
length: 3.68,
crew: '1',
passengers: '1',
maxAtmospheringSpeed: 350,
cargoCapacity: 200,
consumables: 'none' },
{ id: 'dmVoaWNsZXM6NDU=',
name: 'Koro-2 Exodrive airspeeder',
model: 'Koro-2 Exodrive airspeeder',
vehicleClass: 'airspeeder',
manufacturers: [ 'Desler Gizh Outworld Mobility Corporation' ],
costInCredits: null,
length: 6.6,
crew: '1',
passengers: '1',
maxAtmospheringSpeed: 800,
cargoCapacity: 80,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NDY=',
name: 'XJ-6 airspeeder',
model: 'XJ-6 airspeeder',
vehicleClass: 'airspeeder',
manufacturers: [ 'Narglatch AirTech prefabricated kit' ],
costInCredits: null,
length: 6.23,
crew: '1',
passengers: '1',
maxAtmospheringSpeed: 720,
cargoCapacity: null,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NTA=',
name: 'LAAT/i',
model: 'Low Altitude Assault Transport/infrantry',
vehicleClass: 'gunship',
manufacturers: [ 'Rothana Heavy Engineering' ],
costInCredits: null,
length: 17.4,
crew: '6',
passengers: '30',
maxAtmospheringSpeed: 620,
cargoCapacity: 170,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NTE=',
name: 'LAAT/c',
model: 'Low Altitude Assault Transport/carrier',
vehicleClass: 'gunship',
manufacturers: [ 'Rothana Heavy Engineering' ],
costInCredits: null,
length: 28.82,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 620,
cargoCapacity: 40000,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NTM=',
name: 'AT-TE',
model: 'All Terrain Tactical Enforcer',
vehicleClass: 'walker',
manufacturers: [ 'Rothana Heavy Engineering', 'Kuat Drive Yards' ],
costInCredits: null,
length: 13.2,
crew: '6',
passengers: '36',
maxAtmospheringSpeed: 60,
cargoCapacity: 10000,
consumables: '21 days' },
{ id: 'dmVoaWNsZXM6NTQ=',
name: 'SPHA',
model: 'Self-Propelled Heavy Artillery',
vehicleClass: 'walker',
manufacturers: [ 'Rothana Heavy Engineering' ],
costInCredits: null,
length: 140,
crew: '25',
passengers: '30',
maxAtmospheringSpeed: 35,
cargoCapacity: 500,
consumables: '7 days' },
{ id: 'dmVoaWNsZXM6NTU=',
name: 'Flitknot speeder',
model: 'Flitknot speeder',
vehicleClass: 'speeder',
manufacturers: [ 'Huppla Pasa Tisc Shipwrights Collective' ],
costInCredits: 8000,
length: 2,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 634,
cargoCapacity: null,
consumables: 'unknown' },
{ id: 'dmVoaWNsZXM6NTY=',
name: 'Neimoidian shuttle',
model: 'Sheathipede-class transport shuttle',
vehicleClass: 'transport',
manufacturers: [ 'Haor Chall Engineering' ],
costInCredits: null,
length: 20,
crew: '2',
passengers: '6',
maxAtmospheringSpeed: 880,
cargoCapacity: 1000,
consumables: '7 days' }]