export const starshipsSearch = [ { id: 'c3RhcnNoaXBzOjI=',
name: 'CR90 corvette',
model: 'CR90 corvette',
starshipClass: 'corvette',
manufacturers: [ 'Corellian Engineering Corporation' ],
costInCredits: 3500000,
length: 150,
crew: '165',
passengers: '600',
maxAtmospheringSpeed: 950,
hyperdriveRating: 2,
MGLT: 60,
cargoCapacity: 3000000,
consumables: '1 year' },
{ id: 'c3RhcnNoaXBzOjM=',
name: 'Star Destroyer',
model: 'Imperial I-class Star Destroyer',
starshipClass: 'Star Destroyer',
manufacturers: [ 'Kuat Drive Yards' ],
costInCredits: 150000000,
length: 1600,
crew: '47060',
passengers: '0',
maxAtmospheringSpeed: 975,
hyperdriveRating: 2,
MGLT: 60,
cargoCapacity: 36000000,
consumables: '2 years' },
{ id: 'c3RhcnNoaXBzOjU=',
name: 'Sentinel-class landing craft',
model: 'Sentinel-class landing craft',
starshipClass: 'landing craft',
manufacturers: [ 'Sienar Fleet Systems', 'Cyngus Spaceworks' ],
costInCredits: 240000,
length: 38,
crew: '5',
passengers: '75',
maxAtmospheringSpeed: 1000,
hyperdriveRating: 1,
MGLT: 70,
cargoCapacity: 180000,
consumables: '1 month' },
{ id: 'c3RhcnNoaXBzOjk=',
name: 'Death Star',
model: 'DS-1 Orbital Battle Station',
starshipClass: 'Deep Space Mobile Battlestation',
manufacturers:
 [ 'Imperial Department of Military Research',
   'Sienar Fleet Systems' ],
costInCredits: 1000000000000,
length: 120000,
crew: '342953',
passengers: '843342',
maxAtmospheringSpeed: null,
hyperdriveRating: 4,
MGLT: 10,
cargoCapacity: 1000000000000,
consumables: '3 years' },
{ id: 'c3RhcnNoaXBzOjEw',
name: 'Millennium Falcon',
model: 'YT-1300 light freighter',
starshipClass: 'Light freighter',
manufacturers: [ 'Corellian Engineering Corporation' ],
costInCredits: 100000,
length: 34.37,
crew: '4',
passengers: '6',
maxAtmospheringSpeed: 1050,
hyperdriveRating: 0.5,
MGLT: 75,
cargoCapacity: 100000,
consumables: '2 months' },
{ id: 'c3RhcnNoaXBzOjEx',
name: 'Y-wing',
model: 'BTL Y-wing',
starshipClass: 'assault starfighter',
manufacturers: [ 'Koensayr Manufacturing' ],
costInCredits: 134999,
length: 14,
crew: '2',
passengers: '0',
maxAtmospheringSpeed: null,
hyperdriveRating: 1,
MGLT: 80,
cargoCapacity: 110,
consumables: '1 week' },
{ id: 'c3RhcnNoaXBzOjEy',
name: 'X-wing',
model: 'T-65 X-wing',
starshipClass: 'Starfighter',
manufacturers: [ 'Incom Corporation' ],
costInCredits: 149999,
length: 12.5,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 1050,
hyperdriveRating: 1,
MGLT: 100,
cargoCapacity: 110,
consumables: '1 week' },
{ id: 'c3RhcnNoaXBzOjEz',
name: 'TIE Advanced x1',
model: 'Twin Ion Engine Advanced x1',
starshipClass: 'Starfighter',
manufacturers: [ 'Sienar Fleet Systems' ],
costInCredits: null,
length: 9.2,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 1200,
hyperdriveRating: 1,
MGLT: 105,
cargoCapacity: 150,
consumables: '5 days' },
{ id: 'c3RhcnNoaXBzOjE1',
name: 'Executor',
model: 'Executor-class star dreadnought',
starshipClass: 'Star dreadnought',
manufacturers: [ 'Kuat Drive Yards', 'Fondor Shipyards' ],
costInCredits: 1143350000,
length: 19000,
crew: '279144',
passengers: '38000',
maxAtmospheringSpeed: null,
hyperdriveRating: 2,
MGLT: 40,
cargoCapacity: 250000000,
consumables: '6 years' },
{ id: 'c3RhcnNoaXBzOjE3',
name: 'Rebel transport',
model: 'GR-75 medium transport',
starshipClass: 'Medium transport',
manufacturers: [ 'Gallofree Yards', 'Inc.' ],
costInCredits: null,
length: 90,
crew: '6',
passengers: '90',
maxAtmospheringSpeed: 650,
hyperdriveRating: 4,
MGLT: 20,
cargoCapacity: 19000000,
consumables: '6 months' },
{ id: 'c3RhcnNoaXBzOjIx',
name: 'Slave 1',
model: 'Firespray-31-class patrol and attack',
starshipClass: 'Patrol craft',
manufacturers: [ 'Kuat Systems Engineering' ],
costInCredits: null,
length: 21.5,
crew: '1',
passengers: '6',
maxAtmospheringSpeed: 1000,
hyperdriveRating: 3,
MGLT: 70,
cargoCapacity: 70000,
consumables: '1 month' },
{ id: 'c3RhcnNoaXBzOjIy',
name: 'Imperial shuttle',
model: 'Lambda-class T-4a shuttle',
starshipClass: 'Armed government transport',
manufacturers: [ 'Sienar Fleet Systems' ],
costInCredits: 240000,
length: 20,
crew: '6',
passengers: '20',
maxAtmospheringSpeed: 850,
hyperdriveRating: 1,
MGLT: 50,
cargoCapacity: 80000,
consumables: '2 months' },
{ id: 'c3RhcnNoaXBzOjIz',
name: 'EF76 Nebulon-B escort frigate',
model: 'EF76 Nebulon-B escort frigate',
starshipClass: 'Escort ship',
manufacturers: [ 'Kuat Drive Yards' ],
costInCredits: 8500000,
length: 300,
crew: '854',
passengers: '75',
maxAtmospheringSpeed: 800,
hyperdriveRating: 2,
MGLT: 40,
cargoCapacity: 6000000,
consumables: '2 years' },
{ id: 'c3RhcnNoaXBzOjI3',
name: 'Calamari Cruiser',
model: 'MC80 Liberty type Star Cruiser',
starshipClass: 'Star Cruiser',
manufacturers: [ 'Mon Calamari shipyards' ],
costInCredits: 104000000,
length: 1200,
crew: '5400',
passengers: '1200',
maxAtmospheringSpeed: null,
hyperdriveRating: 1,
MGLT: 60,
cargoCapacity: null,
consumables: '2 years' },
{ id: 'c3RhcnNoaXBzOjI4',
name: 'A-wing',
model: 'RZ-1 A-wing Interceptor',
starshipClass: 'Starfighter',
manufacturers: [ 'Alliance Underground Engineering', 'Incom Corporation' ],
costInCredits: 175000,
length: 9.6,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 1300,
hyperdriveRating: 1,
MGLT: 120,
cargoCapacity: 40,
consumables: '1 week' },
{ id: 'c3RhcnNoaXBzOjI5',
name: 'B-wing',
model: 'A/SF-01 B-wing starfighter',
starshipClass: 'Assault Starfighter',
manufacturers: [ 'Slayn & Korpil' ],
costInCredits: 220000,
length: 16.9,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 950,
hyperdriveRating: 2,
MGLT: 91,
cargoCapacity: 45,
consumables: '1 week' },
{ id: 'c3RhcnNoaXBzOjMx',
name: 'Republic Cruiser',
model: 'Consular-class cruiser',
starshipClass: 'Space cruiser',
manufacturers: [ 'Corellian Engineering Corporation' ],
costInCredits: null,
length: 115,
crew: '9',
passengers: '16',
maxAtmospheringSpeed: 900,
hyperdriveRating: 2,
MGLT: null,
cargoCapacity: null,
consumables: 'unknown' },
{ id: 'c3RhcnNoaXBzOjMy',
name: 'Droid control ship',
model: 'Lucrehulk-class Droid Control Ship',
starshipClass: 'Droid control ship',
manufacturers: [ 'Hoersch-Kessel Drive', 'Inc.' ],
costInCredits: null,
length: 3170,
crew: '175',
passengers: '139000',
maxAtmospheringSpeed: null,
hyperdriveRating: 2,
MGLT: null,
cargoCapacity: 4000000000,
consumables: '500 days' },
{ id: 'c3RhcnNoaXBzOjM5',
name: 'Naboo fighter',
model: 'N-1 starfighter',
starshipClass: 'Starfighter',
manufacturers: [ 'Theed Palace Space Vessel Engineering Corps' ],
costInCredits: 200000,
length: 11,
crew: '1',
passengers: '0',
maxAtmospheringSpeed: 1100,
hyperdriveRating: 1,
MGLT: null,
cargoCapacity: 65,
consumables: '7 days' }]