export const personsSearch = [
    { 
        id: 'cGVvcGxlOjE=',
        name: 'Luke Skywalker',
        birthYear: '19BBY',
        eyeColor: 'blue',
        gender: 'male',
        hairColor: 'blond',
        height: 172,
        mass: 77,
        skinColor: 'fair' 
    },
    { 
        id: 'cGVvcGxlOjI=',
        name: 'C-3PO',
        birthYear: '112BBY',
        eyeColor: 'yellow',
        gender: 'n/a',
        hairColor: 'n/a',
        height: 167,
        mass: 75,
        skinColor: 'gold' },
    {
        id: 'cGVvcGxlOjM=',
        name: 'R2-D2',
        birthYear: '33BBY',
        eyeColor: 'red',
        gender: 'n/a',
        hairColor: 'n/a',
        height: 96,
        mass: 32,
        skinColor: 'white, blue' },
    { 
        id: 'cGVvcGxlOjQ=',
        name: 'Darth Vader',
        birthYear: '41.9BBY',
        eyeColor: 'yellow',
        gender: 'male',
        hairColor: 'none',
        height: 202,
        mass: 136,
        skinColor: 'white' },
    { 
        id: 'cGVvcGxlOjU=',
        name: 'Leia Organa',
        birthYear: '19BBY',
        eyeColor: 'brown',
        gender: 'female',
        hairColor: 'brown',
        height: 150,
        mass: 49,
        skinColor: 'light' },
    { 
        id: 'cGVvcGxlOjY=',
        name: 'Owen Lars',
        birthYear: '52BBY',
        eyeColor: 'blue',
        gender: 'male',
        hairColor: 'brown, grey',
        height: 178,
        mass: 120,
        skinColor: 'light' },
    { 
        id: 'cGVvcGxlOjc=',
        name: 'Beru Whitesun lars',
        birthYear: '47BBY',
        eyeColor: 'blue',
        gender: 'female',
        hairColor: 'brown',
        height: 165,
        mass: 75,
        skinColor: 'light' },
    { 
        id: 'cGVvcGxlOjg=',
        name: 'R5-D4',
        birthYear: 'unknown',
        eyeColor: 'red',
        gender: 'n/a',
        hairColor: 'n/a',
        height: 97,
        mass: 32,
        skinColor: 'white, red' },
    { 
        id: 'cGVvcGxlOjk=',
        name: 'Biggs Darklighter',
        birthYear: '24BBY',
        eyeColor: 'brown',
        gender: 'male',
        hairColor: 'black',
        height: 183,
        mass: 84,
        skinColor: 'light' },
    { 
        id: 'cGVvcGxlOjEw',
        name: 'Obi-Wan Kenobi',
        birthYear: '57BBY',
        eyeColor: 'blue-gray',
        gender: 'male',
        hairColor: 'auburn, white',
        height: 182,
        mass: 77,
        skinColor: 'fair' },
    { 
        id: 'cGVvcGxlOjEx',
        name: 'Anakin Skywalker',
        birthYear: '41.9BBY',
        eyeColor: 'blue',
        gender: 'male',
        hairColor: 'blond',
        height: 188,
        mass: 84,
        skinColor: 'fair' 
    }
] 